server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: C:/Users/wito/Desktop/config
          # uri: file://home/wito/web/java/beginners-guide-to-spring-cloud
#          searchPaths: config